### ISSUE TITLE
High and Low parameters 

### ISSUE THREAD

**Issue by bickmox** [wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration#10]
Is there a way to changes the high and low settings on the glucose trend chart? For example the low reading is 4.4 mmol (red dot appears on chart) where as I would like to set to 4.0.

**Comment by FreDiabetics** [comment]
I'm working on a solution for that. :)

**Comment by FreDiabetics** [comment]
I just had a littlde thought about the paramters for high and low. I will work something out today. I will give the permission to set the high and low paramters in tasker so that everyone should be able to use the own paramters.... 
my brain just got lighten up :D :D  will comment after updating all the depending sources :)

**Comment by FreDiabetics** [comment]
I was able to get things sorted. There are a few steps needed to get all working on your side. 

*  **First Update your **xDrip+ Watchmaker Tasker Project** [click here](https://github.com/wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration/wiki/3.1-Update-Tasker-Project-(EN)) for update instructions** 
* **after that [click here](https://github.com/wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration/wiki/1.1-Apps-&-Settings-(EN)#set-the-target-area) then read the steps to set your target area**

At the moment only the **[xDrip Glucose Quarantine](https://getwatchmaker.com/watch/sSJp9UdotU)** Watchface is able to work with the new editable target area. My plan is to update all the other watchfaces as well as fast as I can. Should be done until tomorrow evening hopefully 

I hope this is what you were looking for :)

**Comment by bickmox** [comment]
Hi. Link to Tasker update doesnt work for me. On a side note, the 24hr clock is not working in the quarantine face.

**Comment by FreDiabetics** [comment]
solved that problem ;)
