### ISSUE TITLE
24hr Clock

### ISSUE THREAD

**Issue by bickmox** [wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration#11]
24 hour clock not working. Goes from 01:00pm to 01:00 when toggling between formats.

**Comment by FreDiabetics** [comment]
can you specify the watchface?

**Comment by FreDiabetics** [comment]
there is no problem with the time format at the glucose quarantine watchface. I have uploaded it again. should work

**Comment by bickmox** [comment]
Hi. This is still not resolved in the quarantine watchface. I was the clock to read 24hr format 14:00, 15:00 etc. Instead 02:00 or 03:00 showing on face regardless. When I press the time, pm appears but the numbers stay the same.
