### ISSUE TITLE
Blood glocose dont update

### ISSUE THREAD

**Issue by jenny3883** [wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration#3]
![20200404_013109](https://user-images.githubusercontent.com/36422510/78419468-16132b80-7614-11ea-8a4d-cdbae320f0ab.jpg)
The bg dont update. Any idea why?

**Comment by FreDiabetics** [comment]
Just try opening the watchmaker app and click the button to manually update the values.

Please delete your current Watchface and resync them from my profile.  Also think about reimporting the tasker task. I have updated everything so now everything should work. See the wiki for info

I have made some really important changes in the new Tasker Project. Please use only the actual version.

Check the Wiki **[here](https://github.com/wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration/wiki)** or go directly to Taskernet by clicking **[here](https://taskernet.com/shares/?user=AS35m8mlt5xx0ME%2BtNTXK6rFnQPs1RUb38m9tui3GLZpydqGl3C7iL1YYOsaI8lQbmAxMf%2B4&id=Project%3AxDrip%2B+Watchmaker+Project)** to import the actual Tasker-project
