### ISSUE TITLE
Missing Arrow Direction updates

### ISSUE THREAD

**Issue by stucrooks** [wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration#4]
Hi - first of all, this is amazing the work that you have done to get all this working.  Thanks you so much.  My son has type 1 and I am monitoring his use from a follower on xDrip and have now been able to setup the watch faces to work with my phone as well.

The only issue I have is that the arrow on the watch face indicating which direction he is heading doesn't change from Flat, even though xDrip has a different arrow.  I've has a look and everything else is updating successfully.

Any ideas?  
Many thanks.

**Comment by stucrooks** [comment]
Hi, I fixed the arrow issue.  The face was looking at a variable that didn't exist.  Updated to the XTRENDTEXT and all working now.

Another quick question, what fires the request for the watchface to go and get the updated figures?  Is it a script that runs when the face is shown?  Can this be scheduled for every 15mins?  I'm finding battery life a real issue on Galaxy S2.  
Thanks
Stu

**Comment by FreDiabetics** [comment]
Yes that is for pointing me there ;) I have updated everything and now it should work fine again
