### ISSUE TITLE
Watchface Issue

### ISSUE THREAD

**Issue by djregehr** [wagnefrede/xDrip--Tasker-Tizen-Watchface-Integration#6]
I installed your watchface and downloaded all the programs and paid for the various services.  The information shows in the tasker, but when I load the watch face from watchmaker it has some errors.  I have re-installed each program and re-installed the tasker profile with the same results.  Here is a picture of my watchface.  I have tried each of your watchfaces with the same results. What am I doing wrong???    Samsung S10+, Fossil Gen 5 watch, WearOS 2.17
 
![20200507_114129 1](https://user-images.githubusercontent.com/64940387/81321129-d054e300-9057-11ea-8e45-fedd652ae3cc.jpg)

![20200506_212615 1](https://user-images.githubusercontent.com/64940387/81320653-270ded00-9057-11ea-978a-0eab23be53ae.jpg)

**Comment by FreDiabetics** [comment]
This is no watchface error. Ist caused by bad Settings made by yourself 😉 Long press on the watchface to enter watchface overview, above the watchmaker Watchface you can press a Little gear. Then select complictaions and turn them off. After that the Grey shapes wit „old(2d)d“ should dissapear.

**Comment by FreDiabetics** [comment]
Check [this](https://watchmaker.haz.wiki/complications) out there you can read about aAndroid Wear Complictaions ;)

**Comment by djregehr** [comment]
Thank You!

**Comment by djregehr** [comment]
Thank You!  I figured it was something I was doing wrong.  It works fine now.
